version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - "./public:/var/www/html"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - php
    networks:
      - app-network

  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./public:/var/www/html"
      - "./php:/var/www/html/php"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
